apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: maisfit-prod
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/maisfit`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: maisfit-prod-strip-prefix
